#!/usr/bin/env bash
#installing and configuring nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx restart
sudo echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html
sudo service ngnix restart