#!/usr/bin/env bash
# HTTP response contains a custom header (on web-01 and web-02)
server=$(hostname)
not_found="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
header="server {\n\tadd_header X-Served-By $server;"

sudo apt-get update -y
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
sudo chmod 777 /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo mkdir -p /var/www/html
sudo touch /var/www/html/custom_404.html
sudo chmod 777 /var/www/html/custom_404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$not_found/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$header/" /etc/nginx/sites-available/default
sudo service nginx restart
