#!/usr/bin/env bash
#prints Best school except fr the 4th time and eight time
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ];then
		echo "bad luck"
	else 
		if [ $i -eq 7 ];then
			echo "good luck"
		else
			echo "Best School"
		fi
	fi
	i=$((i+1))
done
