#!/usr/bin/env bash
#Display first 20 integers
number=1
while [ $number -le 20 ]
do
	case $number in
		4)
			echo "4"
			echo "bad luck from China"
			number=$((number+1));;
		9)
			echo "9"
			echo "bad luck from Japan"
			number=$((number+1));;
		17)
			echo "17"
			echo "bad luck from Italy"
			number=$((number+1));;
		*)
			echo "$number"
			number=$((number+1));;
	esac
done
