#!/usr/bin/env bash
#determining the local host and facebook 's address
if [ -f "/.dockerenv" ]; then
	printf "127.0.0.2(\t){1,10}localhost(|t){0,10}\n8.8.8.8   facebook.com\n8.8.8.8   www.facebook.com" | sudo tee -a /etc/hosts
fi
