#!/bin/env bash

sed -i 's/user  nginx;/user  nginx;/g' /etc/nginx/nginx.conf

sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/conf.d/default.conf

service nginx start

service nginx status

